# Generated by Django 4.2.26 on 2025-11-29 05:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_corte', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Número del Corte (1, 2, 3)')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='Porcentaje de peso en la nota final (0.01 a 100.00)')),
            ],
            options={
                'verbose_name': 'Corte de Evaluación',
                'verbose_name_plural': 'Cortes de Evaluación',
                'db_table': 'corte',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código Estudiantil')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('creditos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='NotaIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_valor', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Valor de la Nota (0.00 a 5.00)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.corte')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materia')),
            ],
            options={
                'verbose_name': 'Nota Individual',
                'verbose_name_plural': 'Notas Individuales',
                'db_table': 'nota_individual',
            },
        ),
        migrations.AddField(
            model_name='corte',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materia', verbose_name='Materia'),
        ),
        migrations.CreateModel(
            name='NotaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materia')),
            ],
            options={
                'verbose_name': 'Nota Final',
                'verbose_name_plural': 'Notas Finales',
                'db_table': 'nota_final',
                'unique_together': {('estudiante', 'materia')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='corte',
            unique_together={('materia', 'numero_corte')},
        ),
    ]
